apiVersion: v1
kind: Service
metadata:
  name: united-airlines-service
spec:
  selector:
    app: united-airlines
  ports:
    - protocol: TCP
      port: 80 # The Port that Application listens to Inside the Container
      targetPort: 8080 # The Container Port where the App is Running
  type: LoadBalancer